__tags = {
    "a": False,
    "abbr": False,
    "acronym": False,
    "address": False,
    "applet": False,
    "area": True,
    "article": False,
    "aside": False,
    "audio": False,
    "b": False,
    "base": True,
    "basefont": True,
    "bdi": False,
    "bdo": False,
    "big": False,
    "blockquote": False,
    "body": False,
    "br": True,
    "button": False,
    "canvas": False,
    "caption": False,
    "center": False,
    "cite": False,
    "code": False,
    "col": True,
    "colgroup": False,
    "data": False,
    "datalist": False,
    "dd": False,
    "del": False,
    "details": False,
    "dfn": False,
    "dialog": False,
    "dir": False,
    "div": False,
    "dl": False,
    "dt": False,
    "em": False,
    "embed": True,
    "fieldset": False,
    "figcaption": False,
    "figure": False,
    "font": False,
    "footer": False,
    "form": False,
    "frame": False,
    "frameset": False,
    "h1": False,
    "h2": False,
    "h3": False,
    "h4": False,
    "h5": False,
    "h6": False,
    "head": False,
    "header": False,
    "hr": True,
    "html": False,
    "i": False,
    "iframe": False,
    "img": True,
    "input": True,
    "ins": False,
    "kbd": False,
    "label": False,
    "legend": False,
    "li": False,
    "link": True,
    "main": False,
    "map": False,
    "mark": False,
    "meta": True,
    "meter": False,
    "nav": False,
    "noframes": False,
    "noscript": False,
    "object": False,
    "ol": False,
    "optgroup": False,
    "option": False,
    "output": False,
    "p": False,
    "param": True,
    "picture": False,
    "pre": False,
    "progress": False,
    "q": False,
    "rp": False,
    "rt": False,
    "ruby": False,
    "s": False,
    "samp": False,
    "script": False,
    "section": False,
    "select": False,
    "small": False,
    "source": True,
    "span": False,
    "strike": False,
    "strong": False,
    "style": False,
    "sub": False,
    "summary": False,
    "sup": False,
    "table": False,
    "tbody": False,
    "td": False,
    "template": False,
    "textarea": False,
    "tfoot": False,
    "th": False,
    "thead": False,
    "time": False,
    "title": False,
    "tr": False,
    "track": True,
    "tt": False,
    "u": False,
    "ul": False,
    "var": False,
    "video": False,
    "wbr": True,
}

tags = {
    "a": [False, ["href"]],
    "abbr": [False, []],
    "acronym": [False, []],
    "address": [False, []],
    "applet": [False, ["alt", "height", "name", "width"]],
    "area": [True, ["alt", "coords", "href", "shape"]],
    "article": [False, []],
    "aside": [False, []],
    "audio": [False, ["src"]],
    "b": [False, []],
    "base": [True, ["href"]],
    "basefont": [True, []],
    "bdi": [False, []],
    "bdo": [False, []],
    "big": [False, []],
    "blockquote": [False, []],
    "body": [False, []],
    "br": [True, []],
    "button": [False, ["name", "type"]],
    "canvas": [False, ["height", "width"]],
    "caption": [False, []],
    "center": [False, []],
    "cite": [False, []],
    "code": [False, []],
    "col": [True, []],
    "colgroup": [False, []],
    "data": [False, ["value"]],
    "datalist": [False, []],
    "dd": [False, []],
    "del": [False, []],
    "details": [False, []],
    "dfn": [False, []],
    "dialog": [False, []],
    "dir": [False, []],
    "div": [False, []],
    "dl": [False, []],
    "dt": [False, []],
    "em": [False, []],
    "embed": [True, ["src", "type"]],
    "fieldset": [False, []],
    "figcaption": [False, []],
    "figure": [False, []],
    "font": [False, []],
    "footer": [False, []],
    "form": [False, ["action"]],
    "frame": [True, []],
    "frameset": [False, []],
    "h1": [False, []],
    "h2": [False, []],
    "h3": [False, []],
    "h4": [False, []],
    "h5": [False, []],
    "h6": [False, []],
    "head": [False, []],
    "header": [False, []],
    "hr": [True, []],
    "html": [False, []],
    "i": [False, []],
    "iframe": [False, ["src"]],
    "img": [True, ["src", "alt"]],
    "input": [True, ["name", "type"]],
    "ins": [False, []],
    "kbd": [False, []],
    "label": [False, []],
    "legend": [False, []],
    "li": [False, []],
    "link": [True, ["href", "rel"]],
    "main": [False, []],
    "map": [False, ["name"]],
    "mark": [False, []],
    "meta": [True, ["content", "name"]],
    "meter": [False, []],
    "nav": [False, []],
    "noframes": [False, []],
    "noscript": [False, []],
    "object": [False, ["data", "type"]],
    "ol": [False, []],
    "optgroup": [False, ["label"]],
    "option": [False, []],
    "output": [False, ["name"]],
    "p": [False, []],
    "param": [True, ["name"]],
    "picture": [False, []],
    "pre": [False, []],
    "progress": [False, []],
    "q": [False, []],
    "rp": [False, []],
    "rt": [False, []],
    "ruby": [False, []],
    "s": [False, []],
    "samp": [False, []],
    "script": [False, ["src"]],
    "section": [False, []],
    "select": [False, ["name"]],
    "small": [False, []],
    "source": [True, ["src"]],
    "span": [False, []],
    "strong": [False, []],
    "style": [False, []],
    "sub": [False, []],
    "summary": [False, []],
    "sup": [False, []],
    "table": [False, []],
    "tbody": [False, []],
    "td": [False, []],
    "template": [False, []],
    "textarea": [False, ["name"]],
    "tfoot": [False, []],
    "th": [False, []],
    "thead": [False, []],
    "time": [False, []],
    "title": [False, []],
    "tr": [False, []],
    "track": [True, ["src"]],
    "u": [False, []],
    "ul": [False, []],
    "var": [False, []],
    "video": [False, ["src"]],
    "wbr": [True, []]
}